version: "3.7"

services:
  server:
    build: .
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    depends_on:
      - db
  db:
    image: mysql:8
    restart: always
    ports:
      - 3306:3306
    volumes:
      - datavolume:/var/lib/mysql
    env_file: 
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8081
volumes:
  datavolume:
    driver: local